### ISSUE TITLE
Signal Inputs?

### ISSUE THREAD

**Issue by ldw300** [GownerCode/led-taillights#1]
Are signal inputs for pins 6-10 12v power from vehicle? (e.g. reverse light: 12v+ from reverse light circuit to pin 6)

**Comment by fkws-k** [comment]
Hi,
as far as I know, if you touch the Arduino with 12V on any GPIO pin, it's dead. You need to make sure that all the signals are 5V. I solved that issue by using a buck converter to step down the battery voltage to drive the Arduino and then there is a MOSFET driving each signal input with 5V on Source, the GPIO pin on Drain and the 12V signal from the vehicle on Gate. This way, your Arduino sits in a nice protected 5V shell.

**Comment by ldw300** [comment]
Okay thank you.
